package main

import (
	"fmt"

	"github.com/Samy0412/gopractice/exercices"
)

func main() {
	// fmt.Println("Exercice 1 :")
	// fmt.Println(exercices.Split("I have a cat and a dog"))
	// fmt.Println("Exercice 2 :")
	// fmt.Println(exercices.MoreThanFiveLetters([]string{"dog", "elephant", "cat", "hippopotamus", "giraffe"}))
	// fmt.Println("Exercice 3 :")
	// fmt.Println("n=0 :", exercices.Fibonacci(0))
	// fmt.Println("n=1 :", exercices.Fibonacci(1))
	// fmt.Println("n=2 :", exercices.Fibonacci(2))
	// fmt.Println("n=50 :", exercices.Fibonacci(50))
	fmt.Println("Exercice 4 :")
	fmt.Println("n=0 :", exercices.FibonacciMemoized(0))
	fmt.Println("n=1 :", exercices.FibonacciMemoized(1))
	fmt.Println("n=2 :", exercices.FibonacciMemoized(2))
	fmt.Println("n=3 :", exercices.FibonacciMemoized(3))
	fmt.Println("n=4 :", exercices.FibonacciMemoized(4))
	fmt.Println("n=5 :", exercices.FibonacciMemoized(5))
	fmt.Println("n=6 :", exercices.FibonacciMemoized(6))
	fmt.Println("n=7 :", exercices.FibonacciMemoized(7))
	fmt.Println("n=8 :", exercices.FibonacciMemoized(8))
	fmt.Println("n=9 :", exercices.FibonacciMemoized(9))
	fmt.Println("n=10 :", exercices.FibonacciMemoized(10))
	fmt.Println("n=11 :", exercices.FibonacciMemoized(11))
	fmt.Println("n=12 :", exercices.FibonacciMemoized(12))
	fmt.Println("n=13 :", exercices.FibonacciMemoized(13))
	fmt.Println("n=14 :", exercices.FibonacciMemoized(14))
	fmt.Println("n=15 :", exercices.FibonacciMemoized(15))
	fmt.Println("n=16 :", exercices.FibonacciMemoized(16))
	fmt.Println("n=17 :", exercices.FibonacciMemoized(17))
	fmt.Println("n=18 :", exercices.FibonacciMemoized(18))
	fmt.Println("n=19 :", exercices.FibonacciMemoized(19))
	fmt.Println("n=20 :", exercices.FibonacciMemoized(20))
	fmt.Println("n=21 :", exercices.FibonacciMemoized(21))
	fmt.Println("n=22 :", exercices.FibonacciMemoized(22))
	fmt.Println("n=23 :", exercices.FibonacciMemoized(23))
	fmt.Println("n=24 :", exercices.FibonacciMemoized(24))
	fmt.Println("n=25 :", exercices.FibonacciMemoized(25))
	fmt.Println("n=26 :", exercices.FibonacciMemoized(26))
	fmt.Println("n=27 :", exercices.FibonacciMemoized(27))
	fmt.Println("n=28 :", exercices.FibonacciMemoized(28))
	fmt.Println("n=29 :", exercices.FibonacciMemoized(29))
	fmt.Println("n=30 :", exercices.FibonacciMemoized(30))
	fmt.Println("n=31 :", exercices.FibonacciMemoized(31))
	fmt.Println("n=32 :", exercices.FibonacciMemoized(32))
	fmt.Println("n=33 :", exercices.FibonacciMemoized(33))
	fmt.Println("n=34 :", exercices.FibonacciMemoized(34))
	fmt.Println("n=35 :", exercices.FibonacciMemoized(35))
	fmt.Println("n=36 :", exercices.FibonacciMemoized(36))
	fmt.Println("n=37 :", exercices.FibonacciMemoized(37))
	fmt.Println("n=38 :", exercices.FibonacciMemoized(38))
	fmt.Println("n=39 :", exercices.FibonacciMemoized(39))
	fmt.Println("n=40 :", exercices.FibonacciMemoized(40))
	fmt.Println("n=41 :", exercices.FibonacciMemoized(41))
	fmt.Println("n=42 :", exercices.FibonacciMemoized(42))
	fmt.Println("n=43 :", exercices.FibonacciMemoized(43))
	fmt.Println("n=44 :", exercices.FibonacciMemoized(44))
	fmt.Println("n=45 :", exercices.FibonacciMemoized(45))
	fmt.Println("n=46 :", exercices.FibonacciMemoized(46))
	fmt.Println("n=47 :", exercices.FibonacciMemoized(47))
	fmt.Println("n=48 :", exercices.FibonacciMemoized(48))
	fmt.Println("n=49 :", exercices.FibonacciMemoized(49))
	fmt.Println("n=50 :", exercices.FibonacciMemoized(50))

	// fmt.Println("Exercice 5 :")
	// exercices.StartWebServer()
	// fmt.Println("Exercice 6 :")
	// exercices.StartAPI()
}
